version: "3"
services:
  app:
    container_name: ${CONTAINER_NAME}
    environment:
      - PORT=${PORT}
    build: ./app
    ports:
      - "${PORT}:5000"
    # --------
    volumes:
      - ./app:/app
