version: "3"
services:
  app:
    container_name: ${CONTAINER_NAME}
    environment:
      - PORT=${PORT}
    build:
      context: ./app
      dockerfile: Dockerfile  # Vagy a Dockerfile pontos elérési útja
    ports:
      - "${PORT}:5000"
