#!/bin/bash
. .env
if [ $(docker ps -a --filter "name=${CONTAINER_NAME}" --format '{{.Names}}' | grep -w ${CONTAINER_NAME} | wc -l) -eq 1 ]; then
  docker stop ${CONTAINER_NAME}
  # docker rm ${CONTAINER_NAME}
fi

docker build --build-arg PORT=${PORT} -t ${CONTAINER_NAME} ./app

if [ $PRODUCTION == 1 ]
then
  docker run -d -p ${PORT}:5000 --rm --name ${CONTAINER_NAME} -v $(pwd)/src:/src -v $(pwd)/target:/target ${CONTAINER_NAME}
else
  docker run -p ${PORT}:5000 --rm --name ${CONTAINER_NAME} -v $(pwd)/src:/src -v $(pwd)/target:/target ${CONTAINER_NAME}
fi